//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int user_role { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public System.DateTime birth_date { get; set; }
    
        public virtual userrole userrole { get; set; }

        public bool InRoles(string roles)
        {
            UserRepository repository = new UserRepository();

            if (string.IsNullOrWhiteSpace(roles))
            {
                return false;
            }

            var acceptedRolesArray = roles.Split(new []{","}, StringSplitOptions.RemoveEmptyEntries);
            var currUserRole = repository.GetUserRole(this);

            foreach (var role in acceptedRolesArray)
            {
                var hasRole = string.Compare(role, currUserRole) == 0;
                if (hasRole)
                {
                    return true;                    
                }                
            }
            return false;
        }
    }
}
