
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MvcApplication1.Models
{

    public partial class User
    {

        public int ID { get; set; }

        public string Name { get; set; }

        public int User_Role { get; set; }

        public string Password { get; set; }

        public string Email { get; set; }

        public Nullable<System.DateTime> BirthDate { get; set; }

        public virtual UserRole UserRole { get; set; }

    }

}
